## TensorFlow Basics
This Notebook will be introduction of Tensorflow, an open source platform for machine learning. 

In [4]:
import tensorflow as tf

Tensor rank refers to degrees or dimensions in the tensor. 

In [6]:
#This is a scalar or a tensor rank of 0 (0 dimension)
tensor_rank0=tf.Variable(90, tf.int16)

In [7]:
#This is 1 dimension or a tensor rank of 1
tensor_rank1=tf.Variable([360], tf.int16)

In [8]:
#Tensor rank of 2 (2-dimensional), typically refered to as matrices
tensor_rank2=tf.Variable([[360,290], [34,978]], tf.int16)

In [9]:
#Find the rank of the tensor
tf.rank(tensor_rank2)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [10]:
#Find the shape of the tensor
tensor_rank2.shape

TensorShape([2, 2])

The .shape attribute outputs ([2,2]) because in the tensor there are 2 lists with 2 elements in each list.

In [13]:
#Change the shape of the tensor
tensor1=tf.reshape(tensor_rank2, [2,2,1])
print(tensor1)

tf.Tensor(
[[[360]
  [290]]

 [[ 34]
  [978]]], shape=(2, 2, 1), dtype=int32)


This reshapes the data in tensor_rank2 so that there are 2 lists with two lists within that list containing 1 element each.

In [14]:
#Flatten a tensor
tf.reshape(tensor1, [-1])

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([360, 290,  34, 978])>

## References
https://www.freecodecamp.org/learn/machine-learning-with-python/tensorflow/introduction-to-tensorflow
https://www.tensorflow.org/guide/basics

https://developers.google.com/machine-learning/crash-course/first-steps-with-tensorflow/toolkit

